"""
Template Engine - Renders reports using templates

Implements proprietary template rendering algorithms.
Copyright (c) 2026. All rights reserved.
"""

from typing import Dict
from .report_builder import Report, ReportSection


class TemplateEngine:
    """
    Renders reports using proprietary templates.
    
    Supports text, HTML, and Markdown output formats.
    """
    
    def __init__(self):
        """Initialize the template engine"""
        pass
    
    def render_text(self, report: Report) -> str:
        """
        Render report as plain text.
        
        Proprietary text formatting algorithm.
        """
        lines = []
        
        # Header
        lines.append("=" * 80)
        lines.append(report.title.center(80))
        lines.append(report.subtitle.center(80))
        lines.append(f"Generated: {report.timestamp.strftime('%Y-%m-%d %H:%M:%S')}".center(80))
        lines.append("=" * 80)
        lines.append("")
        
        # Sections
        for section in report.sections:
            lines.extend(self._render_section_text(section))
            lines.append("")
        
        # Footer
        lines.append("=" * 80)
        lines.append("ARICCA-X - Automated Research Integrity, Credibility & Compliance Analyzer".center(80))
        lines.append("Copyright (c) 2026. All rights reserved.".center(80))
        lines.append("=" * 80)
        
        return '\n'.join(lines)
    
    def _render_section_text(self, section: ReportSection, indent: int = 0) -> list:
        """Render a section as text"""
        lines = []
        indent_str = "  " * indent
        
        # Section title
        lines.append(f"{indent_str}{section.title}")
        lines.append(f"{indent_str}{'-' * len(section.title)}")
        
        # Content
        for content_line in section.content:
            lines.append(f"{indent_str}{content_line}")
        
        # Subsections
        if section.subsections:
            for subsection in section.subsections:
                lines.append("")
                lines.extend(self._render_section_text(subsection, indent + 1))
        
        return lines
    
    def render_markdown(self, report: Report) -> str:
        """
        Render report as Markdown.
        
        Proprietary Markdown formatting algorithm.
        """
        lines = []
        
        # Header
        lines.append(f"# {report.title}")
        lines.append(f"## {report.subtitle}")
        lines.append(f"*Generated: {report.timestamp.strftime('%Y-%m-%d %H:%M:%S')}*")
        lines.append("")
        lines.append("---")
        lines.append("")
        
        # Sections
        for section in report.sections:
            lines.extend(self._render_section_markdown(section, level=2))
            lines.append("")
        
        # Footer
        lines.append("---")
        lines.append("*Generated by ARICCA-X - Automated Research Integrity, Credibility & Compliance Analyzer*")
        lines.append("")
        lines.append("Copyright (c) 2026. All rights reserved.")
        
        return '\n'.join(lines)
    
    def _render_section_markdown(self, section: ReportSection, level: int = 2) -> list:
        """Render a section as Markdown"""
        lines = []
        
        # Section title
        lines.append(f"{'#' * level} {section.title}")
        lines.append("")
        
        # Content
        for content_line in section.content:
            lines.append(content_line)
        lines.append("")
        
        # Subsections
        if section.subsections:
            for subsection in section.subsections:
                lines.extend(self._render_section_markdown(subsection, level + 1))
        
        return lines
    
    def render_html(self, report: Report) -> str:
        """
        Render report as HTML.
        
        Proprietary HTML template.
        """
        html_parts = []
        
        # HTML header
        html_parts.append("<!DOCTYPE html>")
        html_parts.append("<html lang='en'>")
        html_parts.append("<head>")
        html_parts.append("  <meta charset='UTF-8'>")
        html_parts.append(f"  <title>{report.title}</title>")
        html_parts.append("  <style>")
        html_parts.append(self._get_css_styles())
        html_parts.append("  </style>")
        html_parts.append("</head>")
        html_parts.append("<body>")
        
        # Report header
        html_parts.append("  <div class='header'>")
        html_parts.append(f"    <h1>{report.title}</h1>")
        html_parts.append(f"    <h2>{report.subtitle}</h2>")
        html_parts.append(f"    <p class='timestamp'>Generated: {report.timestamp.strftime('%Y-%m-%d %H:%M:%S')}</p>")
        html_parts.append("  </div>")
        
        # Report content
        html_parts.append("  <div class='content'>")
        for section in report.sections:
            html_parts.extend(self._render_section_html(section))
        html_parts.append("  </div>")
        
        # Footer
        html_parts.append("  <div class='footer'>")
        html_parts.append("    <p>ARICCA-X - Automated Research Integrity, Credibility & Compliance Analyzer</p>")
        html_parts.append("    <p>Copyright (c) 2026. All rights reserved.</p>")
        html_parts.append("  </div>")
        
        html_parts.append("</body>")
        html_parts.append("</html>")
        
        return '\n'.join(html_parts)
    
    def _render_section_html(self, section: ReportSection, level: int = 3) -> list:
        """Render a section as HTML"""
        html = []
        
        html.append(f"    <div class='section'>")
        html.append(f"      <h{level}>{section.title}</h{level}>")
        
        for content_line in section.content:
            html.append(f"      <p>{content_line}</p>")
        
        if section.subsections:
            for subsection in section.subsections:
                html.extend(self._render_section_html(subsection, level + 1))
        
        html.append("    </div>")
        
        return html
    
    def _get_css_styles(self) -> str:
        """Get proprietary CSS styles for HTML reports"""
        return """
        body {
            font-family: Arial, sans-serif;
            line-height: 1.6;
            max-width: 1200px;
            margin: 0 auto;
            padding: 20px;
            background-color: #f5f5f5;
        }
        .header {
            background-color: #2c3e50;
            color: white;
            padding: 30px;
            text-align: center;
            border-radius: 5px;
            margin-bottom: 30px;
        }
        .header h1 {
            margin: 0;
            font-size: 2em;
        }
        .header h2 {
            margin: 10px 0;
            font-size: 1.2em;
            font-weight: normal;
        }
        .timestamp {
            margin: 10px 0 0 0;
            font-size: 0.9em;
            opacity: 0.8;
        }
        .content {
            background-color: white;
            padding: 30px;
            border-radius: 5px;
            box-shadow: 0 2px 5px rgba(0,0,0,0.1);
        }
        .section {
            margin-bottom: 30px;
        }
        .section h3 {
            color: #2c3e50;
            border-bottom: 2px solid #3498db;
            padding-bottom: 10px;
        }
        .section h4 {
            color: #34495e;
        }
        .section p {
            margin: 10px 0;
            color: #555;
        }
        .footer {
            text-align: center;
            margin-top: 30px;
            padding: 20px;
            color: #7f8c8d;
            font-size: 0.9em;
        }
        """
